apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/waj310/training.git'
    targetRevision: main
    path: myapp
  destination:
    server: 'https://3DFD46A55385A4C9919BF5B730E1B826.gr7.us-east-2.eks.amazonaws.com'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
