apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: {{ .Values.service.type | default "ClusterIP"}}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 3000
  selector:
    app: myapp
